spring.application.name=rewardwise-api
server.port=8080
server.servlet.context-path=/rewardwise


spring.datasource.url=jdbc:h2:mem:rewarddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.profiles.active=dev
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hiberbate.format_sql=true

logging.level.root=INFO
logging.level.com.rewardwise.api=DEBUG
reward.points.first-threshold=50
reward.points.second-threshold=100
reward.points.first-multiplier=1
reward.points.second-multiplier=2